#! /usr/bin/env python

import subprocess, argparse, shutil, os, time

parser = argparse.ArgumentParser(description="Clone a new sage install")
parser.add_argument('name', help='the name of your new install')
args = parser.parse_args()
lockfile = ".newsage.lock"

if os.path.exists(lockfile):
    print "Someone else is extracting the tarball; waiting until they have finished."
    print "If you believe that this is in error, delete %s"%lockfile
    while True:
        time.sleep(0.2)
        if not os.path.exists(lockfile):
            print "Lockfile cleared; proceeding."
            break
try:
    with open(lockfile,"a"):
        os.utime(lockfile, None)
    print "Extracting tarball...."
    subprocess.call('ionice lz4 -dc --no-sparse sage-latest.tar.lz4 | tar xf -', shell=True)
    sageloc = "sage-%s"%args.name
    print "Changing name to " + sageloc
    shutil.move("SageMath", sageloc)
finally:
    os.unlink(lockfile)
os.chdir(sageloc)
print "Setting git remotes"
subprocess.call(["git", "remote", "add", "trac", "git://trac.sagemath.org/sage.git"])
subprocess.call(["git", "remote", "set-url", "--push", "trac", "git@trac.sagemath.org:sage.git"])
print "Relocating paths"
subprocess.call(["./relocate-once.py", "-d", os.getcwd()])
